# Generated by Django 2.1.4 on 2019-10-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_column='学号', max_length=20, verbose_name='学号')),
                ('sprofessional', models.CharField(db_column='专业', max_length=20, verbose_name='专业')),
                ('sphone', models.CharField(db_column='手机号', max_length=20, verbose_name='手机号')),
                ('sresults', models.BooleanField(db_column='申请结果', default=0, verbose_name='申请结果')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
            },
        ),
        migrations.CreateModel(
            name='OpenDoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprofessional', models.CharField(db_column='专业', max_length=20, verbose_name='专业')),
                ('sposition', models.CharField(db_column='职位', default='群众', max_length=10, verbose_name='职位')),
                ('spermissions', models.BooleanField(db_column='开门权限', default=0, verbose_name='开门权限')),
            ],
            options={
                'verbose_name': '权限管理',
                'verbose_name_plural': '权限管理',
            },
        ),
        migrations.CreateModel(
            name='Stinfo',
            fields=[
                ('st_id', models.CharField(db_column='学号', max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('st_name', models.CharField(db_column='姓名', max_length=10, verbose_name='姓名')),
                ('st_password', models.CharField(db_column='密码', default='001100', max_length=20, verbose_name='密码')),
                ('st_gender', models.CharField(db_column='性别', default='男', max_length=2, verbose_name='性别')),
                ('st_college', models.CharField(db_column='学院', max_length=10, verbose_name='学院')),
                ('st_major', models.CharField(db_column='专业', max_length=20, verbose_name='专业')),
                ('st_class', models.IntegerField(db_column='班级', default=1, verbose_name='班级')),
                ('st_position', models.CharField(db_column='职位', default='群众', max_length=10, verbose_name='职位')),
            ],
        ),
        migrations.AddField(
            model_name='opendoor',
            name='fsid',
            field=models.ForeignKey(db_column='学号', on_delete=django.db.models.deletion.CASCADE, to='ksglapp.Stinfo', verbose_name='学号'),
        ),
    ]
