# Generated by Django 2.1.4 on 2019-10-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksglapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stinfo',
            options={'verbose_name': '学生管理', 'verbose_name_plural': '学生管理'},
        ),
    ]
